endless loop in bind_table
abap2xlsx/abap2xlsx pull request #1044
Opened 2022-07-11 20:03 UTC by sandraros

Fix #1043

2022-07-11 20:14 UTC, AndreaBorgia-Abo commented
On it! While I test this, fancy looking at that date/time format PR?

2022-07-11 22:09 UTC, AndreaBorgia-Abo requested changes

2022-07-11 22:09 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +                   <scrtxt3>          TYPE any.
```suggestion
                   <scrtxt1> TYPE any,
                   <scrtxt2> TYPE any,
                   <scrtxt3> TYPE any.
```

2022-07-11 22:09 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +                   <scrtxt3>          TYPE any.
Most likely a pretty-printer misfire

2022-07-11 22:09 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +        lv_scrtext_l_initial = substring( val = lv_scrtext_l_initial len = 38 ).
It works, with the test program as supplied.

I tweaked it [a little bit ](https://github.com/AndreaBorgia-Abo/ABAP-Examples/blob/main/src/github/zabo_abap2xlsx_bug_1043.prog.abap)and managed to get weird labels, with an asterisk in them: more than 100 fields and 38 as cutoff value does not work well. To get back to a sane behaviour, I had to lower the cutoff to 37.

I'd say we need to find the lowest between the maximum number of fields in an internal table for SAP (1024?) and the maximum number of columns in Excel (16k?), see how many chars this number takes and then work backwards from the max length of the catalog description... TLDR: 35 is probably fine.
Another option is to count the number of entries in the catalog and adjust the cutoff value as needed but, and I say so myself, this is way overkill although likely foolproof.

2022-07-12 06:22 UTC, sandraros commented on src/zcl_excel_worksheet.clas.abap
> +                   <scrtxt3>          TYPE any.
I don't get why you want to unalign the TYPE keyword. Current alignment is OK for me:
```abap
    FIELD-SYMBOLS: <ls_field_catalog> TYPE zexcel_s_fieldcatalog,
                   <scrtxt1>          TYPE any,
                   ...
```

2022-07-12 06:40 UTC, sandraros commented on src/zcl_excel_worksheet.clas.abap
> +        lv_scrtext_l_initial = substring( val = lv_scrtext_l_initial len = 38 ).
My assumption was that it's unlikely to have 100 components with the same text, so that to keep the code simple.

If we go for a fix without bug, I'd prefer a nice suffix logic to not cut characters uselessly. I couldn't think of a simple way to right align a suffix to a field without hardcoding the length. If the final code to add the suffix is a little bit complex, maybe we can simply create a separate private method to add a suffix of any length to a text of any length.

2022-07-12 19:38 UTC, sandraros commented on src/zcl_excel_worksheet.clas.abap
> +        lv_scrtext_l_initial = substring( val = lv_scrtext_l_initial len = 38 ).
Proposing code to handle more than 100 same texts. Hope it works.

2022-07-13 17:46 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +                   <scrtxt3>          TYPE any.
Never mind, my mistake: I assumed it was ok before and, also, tried to undo it which is not really obvious with GH suggestions.

2022-07-13 17:59 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
>      " Due restrinction of new table object we cannot have two column with the same name
```suggestion
    " Due to restrictions in new table object we cannot have two columns with the same name
```

2022-07-13 18:24 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +        lv_scrtext_l_initial = substring( val = lv_scrtext_l_initial len = 38 ).
You went for the overkill suggestion, I like that :)

2022-07-13 18:26 UTC, AndreaBorgia-Abo approved these changes
Super, it works nicely and looks readable!
Here are the relevant transitions:
```
Text Text Text Text Text Text Text Tex 9
Text Text Text Text Text Text Text Tex10
Text Text Text Text Text Text Text Tex99
Text Text Text Text Text Text Text Te100
```
LGTM!

2022-07-13 18:28 UTC, merged

2022-07-13 19:23 UTC, sandraros commented
@AndreaBorgia-Abo Thanks a lot for suggestions and fast review!