UnitTests ltc_normalize_column_heading were broken
abap2xlsx/abap2xlsx pull request #1079
Opened 2023-01-27 14:08 UTC by rplantiko

After having introduced a new column `column_name` in the zexcel_s_fieldcatalog (in Commit bca6db9 by user @bigld ), the unit tests of class ltc_normalize_column_heading were broken: the test expectations should have been adapted to the new field `column_name`. 

To find broken unit tests after download of the latest abap2xlsx version is confusing, especially for newcomers. It is best practice, when performing changes on a class, to execute their abap unit tests before uploading them into github.

I have used the opportunity to refactor the test class  ltc_normalize_column_heading - the intentions of the tests should be better readable now.

2023-01-27 16:42 UTC, gregorwolf commented
Hi @rplantiko,

I think we should still avoid inline declarations to have it compatible with 7.02.

Best Regards
Gregor

2023-01-28 07:04 UTC, rplantiko commented
Hi Gregor, so I time-travelled 15 years back in the past, trying to remember how people spoke ABAP in those times. After two attempts, it seems that I finally was understood. ;-)

2023-01-28 07:18 UTC, rplantiko commented
OK, _four_ attempts, not two

2023-01-28 09:40 UTC, rplantiko commented
The pull request had been closed unintentionally (as an unwanted effect of my deletion of a very old fork of abap2xlsx on my account).

2023-01-28 16:15 UTC, sandraros commented
Fix #1072

2023-01-28 16:21 UTC, sandraros commented
Thank you for your contribution. I can't pull locally the branch from your repository (https://github.com/rplantiko/abap2xlsx), I've got the error 404, and I can't see abap2xlsx in your list of repositories. Could you give public access to your repository please? Thank you.

2023-01-28 16:44 UTC, rplantiko commented
Hi Sandra, 

if you want to see my final commit of the file zcl_excel_worksheet.clas.testclasses.abap: this link should work:

https://github.com/abap2xlsx/abap2xlsx/blob/259f3d91839a684b127df06aa4445441389fa48b/src/zcl_excel_worksheet.clas.testclasses.abap

I realized that I had created a fork of abap2xlsx on my user a very long time ago. I have deleted that fork yesterday, as I don't need it. 

I expect it to be possible to apply my changes to the central repository, anyway. 

If it's not possible, I suggest that we close this Pull request, and I open a new one with reference to this one. 

Regards,
Rüdiger

2023-01-28 17:51 UTC, sandraros requested changes
`if_abap_unit_constant` doesn't exist in ABAP 7.52. It will work with `if_aunit_constants` (same attributes).

2023-01-28 17:52 UTC, sandraros commented
Thank you, pulling the commit from ZABAPGIT worked. Could you do the change I just requested please?

2023-01-28 18:36 UTC, rplantiko commented
Indeed, as I had deleted my previous fork (didn't know that it is necessary to have one in order to participate in the code base), I could not add it with this PR. I created a new one to continue the changes.

2023-01-28 18:36 UTC, closed without merging