Make the reader get the Tables
abap2xlsx/abap2xlsx pull request #1159
Opened 2023-11-16 13:26 UTC by sandraros

Fix #1158

2023-11-16 13:42 UTC, sandraros commented
@larshp I don't get what all these abaplint messages are about. Is there anything I should do? Thanks.
![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/56ba3b71-e14c-442f-be2d-c068194c320f)

2023-11-16 14:28 UTC, larshp requested changes, later dismissed

2023-11-16 14:28 UTC, larshp commented on src/zcl_excel_reader_2007.clas.abap
> +    LOOP AT it_tables ASSIGNING <ls_table>.
not 702 compatible

2023-11-16 15:49 UTC, larshp commented on src/zcl_excel_reader_2007.clas.abap
> +      LOOP AT lt_field_catalog ASSIGNING FIELD-SYMBOL(<field>).
not 702 compatible

2023-11-16 16:05 UTC, sandraros commented
@larshp Thanks for the support! :)

2023-12-24 19:26 UTC, sandraros commented
Fix #1168

2023-12-25 15:36 UTC, merged