Fix: after BIND_TABLE no columns in object #730
abap2xlsx/abap2xlsx pull request #731
Opened 2021-02-04 17:16 UTC by RedWolf112

2021-02-04 17:21 UTC, RedWolf112 commented
After method bind_table in the worksheet the columns are empty

2021-02-10 17:40 UTC, gregorwolf commented
Hi @RedWolf112 ,
in which example report can I test the improved behaviour?

2021-02-11 11:22 UTC, RedWolf112 commented
Hi @gregorwolf,

at the moment ther is no test report.
I have to write a new one. 
The test report should use the get_columns_iterator( ) from the worksheet.
Without the fix the columns iterator has no entries.

2021-07-28 15:49 UTC, AndreaBorgia-Abo commented
#781 was merged and resulted in some conflicts, sorry for the inconvenience.

2021-09-11 17:41 UTC, sandraros commented
There is the same issue even after `SET_CELL`, the column collection is empty. To reproduce:
```
REPORT.
DATA: gc_save_file_name TYPE string VALUE 'PR_731.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  SELECT * FROM scarr INTO TABLE @DATA(scarr).
  DATA(lo_excel) = NEW zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_cell( ip_column = 1 ip_row = 1 ip_value = 'a' ).
  DATA(columns_iterator) = lo_worksheet->get_columns_iterator( ).
  ASSERT abap_false = columns_iterator->has_next( ). "<=== no column in the iterator
```
I'm afraid the rows iterator is also concerned.
Maybe we could complete the list of columns/rows when the iterator is instantiated? For information, to know how many rows and columns are in the worksheet, the method `GET_DIMENSION_RANGE` can be used.

2021-11-07 13:25 UTC, sandraros commented
@RedWolf112 @AndreaBorgia-Abo @gregorwolf I investigated more about the columns and rows iterators, and I think the original and current feature is to propose an iterator only for those columns and rows explicitly "added" using `sheet->get_column( 1 )` or `sheet->add_new_column( 1 )`/`sheet->get_row( 1 )` or `sheet->add_new_row( 1 )`, to define column and row attributes, and not to support the cells defined using `SET_CELL`, `BIND_TABLE` and so on. I would prefer a completely different solution from the one proposed here (maybe by calling a new method to explicitly synchronize columns and rows from the cells of the worksheet `sheet_content` attribute). I propose to create an issue to agree first on a solution, and to abandon this PR. Please tell me if you agree to go this way?

2021-11-07 18:41 UTC, AndreaBorgia-Abo commented
I have no objections but @RedWolf112 [might](https://github.com/sapmentors/abap2xlsx/pull/731#issuecomment-777378478)

2021-11-15 07:58 UTC, RedWolf112 commented
I think it's a good solution

2021-12-10 14:28 UTC, sandraros commented
@RedWolf112 @AndreaBorgia-Abo I pushed a new commit/new solution in the original branch. I extended the solution to also handle the methods `GET_ROWS` and `GET_COLUMNS`. I used the updated code snippet above to check the results (test class + output through iterator) but of course it would make more sense if you do other tests. Thank you!

2021-12-21 17:55 UTC, AndreaBorgia-Abo commented
On it... tomorrow morning I be able to test and merge.

2021-12-22 09:47 UTC, AndreaBorgia-Abo requested changes
It works as advertised, I've tried breaking the tests in odd ways but couldn't.
If the suggested changes are accepted, then we can merge. If the reworked version makes use of those variables, please re-request a review.

2021-12-22 09:47 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +          row       TYPE i.
```suggestion
    DATA: row       TYPE i.
```

2021-12-22 09:47 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +
```suggestion

```

2021-12-22 09:47 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +
first_row and last_row are unused and the the DO cycle seems to be correctly terminated via subrc = 8.

2021-12-24 15:20 UTC, AndreaBorgia-Abo approved these changes
LGTM

2021-12-24 15:21 UTC, merged

2022-10-09 14:21 UTC, AndreaBorgia-Abo commented
Rebuilding A4H, had to change cl_object_collection_iterator to zcl_excel_collection_iterator in the test program above, else it wouldn't activate anymore. Funny enough, the same goes for the other MiniSAP, NPL. Pretty sure that at the time it worked fine, I guess changes have invalidated the offending assignments.
(TLDR nothing to see here, move along)