extract font width logic to new class
abap2xlsx/abap2xlsx pull request #882
Opened 2021-11-07 06:03 UTC by larshp

2021-11-07 19:26 UTC, sandraros requested changes
Proposing to rename method (to indicate what exactly is calculated about font), and reorder/reformat data declarations in case in the future we need to compare what has been changed exactly.

2021-11-07 19:26 UTC, sandraros commented on src/zcl_excel_font.clas.abap
> +    FIELD-SYMBOLS <ls_font_metric> TYPE mty_s_font_metric.
When some code is moved, I check by comparing "manually" using notepad++ hence it's important to keep the original order and formatting.
```suggestion
    DATA: ld_cell_value                TYPE zexcel_cell_value,
          ld_style_guid                TYPE zexcel_cell_style,
          ls_stylemapping              TYPE zexcel_s_stylemapping,
          lo_table_object              TYPE REF TO object,
          lo_table                     TYPE REF TO zcl_excel_table,
          ld_table_top_left_column     TYPE zexcel_cell_column,
          ld_table_bottom_right_column TYPE zexcel_cell_column,
          ld_flag_contains_auto_filter TYPE abap_bool VALUE abap_false,
          ld_flag_bold                 TYPE abap_bool VALUE abap_false,
          ld_flag_italic               TYPE abap_bool VALUE abap_false,
          ld_date                      TYPE d,
          ld_date_char                 TYPE c LENGTH 50,
          ld_font_height               TYPE tdfontsize VALUE zcl_excel_font=>lc_default_font_height,
          ld_font_name                 TYPE zexcel_style_font_name VALUE zcl_excel_font=>lc_default_font_name.
```

2021-11-07 19:26 UTC, sandraros commented on src/zcl_excel_font.clas.abap
> +  METHOD calculate.
```suggestion
  METHOD calculate_text_width.
```

2021-11-07 19:26 UTC, sandraros commented on src/zcl_excel_font.clas.abap
> +    CLASS-METHODS calculate
```suggestion
    CLASS-METHODS calculate_text_width
```

2021-11-07 19:26 UTC, sandraros commented on src/zcl_excel_font.clas.testclasses.abap
> +    lv_width = zcl_excel_font=>calculate(
```suggestion
    lv_width = zcl_excel_font=>calculate_text_width(
```

2021-11-07 19:26 UTC, sandraros commented on src/zcl_excel_worksheet.clas.abap
> +    ep_width = zcl_excel_font=>calculate(
```suggestion
    ep_width = zcl_excel_font=>calculate_text_width(
```

2021-11-09 19:11 UTC, sandraros commented on src/zcl_excel_font.clas.abap
> +    FIELD-SYMBOLS <ls_font_metric> TYPE mty_s_font_metric.
I don't know what happened to this proposal, but it's now worse. Now the code declares unused variables. Do I incorrectly propose the suggestion? Proposing again the same code.
```suggestion
    DATA: ld_current_character         TYPE c LENGTH 1,
          lt_itcfc                     TYPE STANDARD TABLE OF itcfc,
          ld_offset                    TYPE i,
          ld_length                    TYPE i,
          ld_uccp                      TYPE i,
          ls_font_metric               TYPE mty_s_font_metric,
          ld_width_from_font_metrics   TYPE i,
          ld_font_family               TYPE itcfh-tdfamily,
          lt_font_families             LIKE STANDARD TABLE OF ld_font_family,
          ls_font_cache                TYPE mty_s_font_cache.

    FIELD-SYMBOLS: <ls_font_cache>  TYPE mty_s_font_cache,
                   <ls_font_metric> TYPE mty_s_font_metric,
                   <ls_itcfc>       TYPE itcfc.
```

2021-11-09 19:14 UTC, sandraros requested changes
It seems there was a little problem when applying the suggestion, now there are unused variables. Suggesting the same proposal.

2021-11-10 04:54 UTC, larshp commented
updated with proposal

2021-11-11 09:19 UTC, sandraros approved these changes
No regression on `ZDEMO_EXCEL31`. LGTM 👍

2021-11-11 09:19 UTC, merged