Sandraros/check demo regressions
abap2xlsx/abap2xlsx pull request #902
Opened 2021-12-04 22:03 UTC by sandraros

2021-12-20 17:44 UTC, AndreaBorgia-Abo commented on src/demos/zdemo_excel_checker.prog.abap
> +            " restart the program completely so that to consider modification/recompile of any ZDEMO_EXCEL program
```suggestion
            " restart the program completely to account for modification/rebuild of any ZDEMO_EXCEL program
```

2021-12-24 18:35 UTC, AndreaBorgia-Abo commented
I'll do the full review over the coming days, stay tuned.

2022-01-03 07:54 UTC, AndreaBorgia-Abo commented
Review time...

2022-01-03 07:54 UTC, sandraros commented
@AndreaBorgia-Abo I forgot to say that I was working on a [second simplest version](https://github.com/abap2xlsx/abap2xlsx/pull/940) to check demo regressions, whose advantage is to not change the demo programs. It's simply based on the Excel files created on the frontend by program ZDEMO_EXCEL. Could you say which solution you prefer?

2022-01-03 10:39 UTC, AndreaBorgia-Abo commented
Sheesh, ended up using this PR as a guinea pig for a [possible abapGit bug](https://github.com/abapGit/abapGit/issues/5233#issuecomment-1004000633) ... I'll check the newer version first, then!

2022-01-03 17:47 UTC, AndreaBorgia-Abo requested changes
Should probably be closed in favour of the newer #940

2022-01-03 17:50 UTC, sandraros commented
Closing in favor of other PR #940

2022-01-03 17:50 UTC, closed without merging