refactor method change_cell_style in zcl_excel_worksheet
abap2xlsx/abap2xlsx pull request #904
Opened 2021-12-07 20:45 UTC by sandraros

Creation of new class `zcl_excel_style_changer` and refactor of `change_cell_style` to use it. There's no fix, no feature change, it helps to go towards #524.

Future plan: with this new class, it will be easy to create a new method `change_area_style` so that to change the style of many cells at a time. That would permit to rewrite `zdemo_excel40`, for the exact same result, instead of calling `set_cell` and `change_cell_style` repeatedly for each cell in 100 rows * 20 columns, the methods `set_area` and `change_area_style` could be called once:
```abap
    lo_worksheet->set_area(
          ip_column_start = 1
          ip_column_end   = 20
          ip_row          = 1
          ip_row_to       = 100
          ip_formula      = 'CHAR(64+COLUMN())&TEXT(ROW(),"       ?0")' ).

    lo_changer = zcl_excel_style_changer=>create( lo_excel ).
    lo_changer->set_fill_filltype( zcl_excel_style_fill=>c_fill_solid ).
    lo_changer->set_fill_fgcolor_rgb( zcl_excel_style_color=>c_yellow ).
    lo_worksheet->change_area_style(
          ip_column_start = 1
          ip_column_end   = 20
          ip_row          = 1
          ip_row_to       = 3
          ip_changer      = lo_changer.

    lo_changer = zcl_excel_style_changer=>create( lo_excel ).
    lo_changer->set_font_color_rgb( zcl_excel_style_color=>c_red ).
    lo_worksheet->change_area_style(
          ip_column_start = 1
          ip_column_end   = 4
          ip_row          = 1
          ip_row_to       = 100
          ip_changer      = lo_changer.
```

2021-12-11 14:10 UTC, AndreaBorgia-Abo requested changes
There seems to be a regression with an export parameter and a couple of commented-out methods I cannot understand.

2021-12-11 14:10 UTC, AndreaBorgia-Abo commented on src/zcl_excel_style_changer.clas.abap
> +*  METHOD get.
I'm not sure I understand the reason behind these two methods, commented out and left there.

2021-12-11 14:10 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> -    ep_guid = me->excel->get_static_cellstyle_guid( ip_cstyle_complete  = complete_style
Where is ep_guid filled in in the refactored code? Debugged twice (new / old) and it seems te be missing.

2021-12-11 14:10 UTC, AndreaBorgia-Abo commented on src/zcl_excel_style_changer.clas.abap
> +*    CLASS-METHODS get
I'm not sure I understand the reason behind these two methods, commented out and left there.

2021-12-11 14:31 UTC, sandraros commented on src/zcl_excel_worksheet.clas.abap
> -    ep_guid = me->excel->get_static_cellstyle_guid( ip_cstyle_complete  = complete_style
You're right, regression, let me fix that.

2021-12-11 14:32 UTC, sandraros commented on src/zcl_excel_style_changer.clas.abap
> +*  METHOD get.
No reason, let me remove them.

2021-12-11 20:28 UTC, sandraros commented on src/zcl_excel_style_changer.clas.abap
> +*  METHOD get.
Done

2021-12-11 20:28 UTC, sandraros commented on src/zcl_excel_worksheet.clas.abap
> -    ep_guid = me->excel->get_static_cellstyle_guid( ip_cstyle_complete  = complete_style
Done

2021-12-11 20:30 UTC, sandraros commented
Program for testing the `ep_guid` parameter returned by `change_cell_style`:
```abap
REPORT.
DATA: lo_excel     TYPE REF TO zcl_excel,
      lo_worksheet TYPE REF TO zcl_excel_worksheet.
CONSTANTS: gc_save_file_name TYPE string VALUE 'PR_904.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  CREATE OBJECT lo_excel.
  lo_worksheet = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_cell( ip_column = 1 ip_row = 1 ip_value = 'A1' ).
  lo_worksheet->set_cell( ip_column = 2 ip_row = 1 ip_value = 'B1' ).
  lo_worksheet->set_cell( ip_column = 3 ip_row = 1 ip_value = 'C1' ).
  DATA(lv_guid) = lo_worksheet->change_cell_style(
      ip_column           = 1
      ip_row              = 1
      ip_fill_filltype    = zcl_excel_style_fill=>c_fill_solid
      ip_fill_fgcolor_rgb = zcl_excel_style_color=>c_yellow ).
  lo_worksheet->set_cell_style( ip_column = 2 ip_row = 1 ip_style = lv_guid ).
  DATA(lv_guid2) = lo_worksheet->change_cell_style(
      ip_column         = 1
      ip_row            = 1
      ip_font_color_rgb = zcl_excel_style_color=>c_red ).
  lo_worksheet->set_cell_style( ip_column = 3 ip_row = 1 ip_style = lv_guid2 ).
  lcl_output=>output( lo_excel ).
```

2021-12-14 21:56 UTC, AndreaBorgia-Abo approved these changes
LGTM

2021-12-14 21:57 UTC, merged