+ change_area_style (same as change_cell_style, but for area)
abap2xlsx/abap2xlsx pull request #922
Opened 2021-12-18 17:18 UTC by sandraros

New method `change_area_style` of `zcl_excel_worksheet`, which combines the methods `change_cell_style` and `set_area_style`. Program `zdemo_excel40` adapted to demonstrate this new method.

This PR is the last before proposing a solution to reduce of code footprint #524.

2021-12-18 17:20 UTC, larshp approved these changes

2021-12-20 11:16 UTC, AndreaBorgia-Abo requested changes
Can be merged after removing the two optional keywords; the naming of the variable is just a personal preference, not a showstopper.

2021-12-20 11:16 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +        !ip_column_start  TYPE simple OPTIONAL
```suggestion
        !ip_column_start  TYPE simple
```

2021-12-20 11:16 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +        !ip_row           TYPE zexcel_cell_row OPTIONAL
```suggestion
        !ip_row           TYPE zexcel_cell_row
```

2021-12-20 11:16 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +        !ip_row           TYPE zexcel_cell_row OPTIONAL
A call with only ip_style_changer would raise ZCX_EXCEL during the conversion of lv_column_start (tried it).
Making at least these two compulsory (like in set_area_formula), setting style for A101 to red but no content works as expected:
![image](https://user-images.githubusercontent.com/25269970/146756605-3ffd2cac-0e00-4909-9794-6c71e0e16027.png)
(the content has been manually added after opening)

2021-12-20 11:16 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +          lv_row_end          TYPE zexcel_cell_row,
```suggestion
          lv_row_to          TYPE zexcel_cell_row,
```

2021-12-20 11:16 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +          lv_row_end          TYPE zexcel_cell_row,
Minor point but it looks better if we follow the naming of the import parameter we're shadowing.
(to avoid messing up the whole text, I'm not changing all occurrences right now)

2021-12-24 09:59 UTC, sandraros commented
Changes done as requested. Please re-check. Thanks!

2021-12-24 11:45 UTC, AndreaBorgia-Abo approved these changes
LGTM

2021-12-24 11:46 UTC, merged