refactor to use new collection classes
abap2xlsx/abap2xlsx pull request #937
Opened 2021-12-29 05:00 UTC by larshp

closes #880

2021-12-31 18:23 UTC, sandraros requested changes
LGTM but class names in CLASS IMPLEMENTATION are all changed to upper case. Is it normal?

2022-01-01 08:21 UTC, larshp commented
its changed by SE80, 

if you'd like to enforce a specific style, suggest enabling https://rules.abaplint.org/keyword_case/, https://github.com/abap2xlsx/abap2xlsx/blob/master/abaplint.json#L109

2022-01-01 10:51 UTC, sandraros requested changes
Changing back to `CLASS zcl_<alllowercase> IMPLEMENTATION`. Proposed lint rule in #941.

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel.clas.abap
> +CLASS ZCL_EXCEL IMPLEMENTATION.
```suggestion
CLASS zcl_excel IMPLEMENTATION.
```

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel_columns.clas.abap
> +CLASS ZCL_EXCEL_COLUMNS IMPLEMENTATION.
```suggestion
CLASS zcl_excel_columns IMPLEMENTATION.
```

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel_comments.clas.abap
> +CLASS ZCL_EXCEL_COMMENTS IMPLEMENTATION.
```suggestion
CLASS zcl_excel_comments IMPLEMENTATION.
```

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel_data_validations.clas.abap
> +CLASS ZCL_EXCEL_DATA_VALIDATIONS IMPLEMENTATION.
```suggestion
CLASS zcl_excel_data_validations IMPLEMENTATION.
```

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel_drawings.clas.abap
> +CLASS ZCL_EXCEL_DRAWINGS IMPLEMENTATION.
```suggestion
CLASS zcl_excel_drawings IMPLEMENTATION.
```

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel_fill_template.clas.abap
> +CLASS ZCL_EXCEL_FILL_TEMPLATE IMPLEMENTATION.
```suggestion
CLASS zcl_excel_fill_template IMPLEMENTATION.
```

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel_ranges.clas.abap
> +CLASS ZCL_EXCEL_RANGES IMPLEMENTATION.
```suggestion
CLASS zcl_excel_ranges IMPLEMENTATION.
```

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel_reader_2007.clas.abap
> +CLASS ZCL_EXCEL_READER_2007 IMPLEMENTATION.
```suggestion
CLASS zcl_excel_reader_2007 IMPLEMENTATION.
```

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel_rows.clas.abap
> +CLASS ZCL_EXCEL_ROWS IMPLEMENTATION.
```suggestion
CLASS zcl_excel_rows IMPLEMENTATION.
```

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel_styles.clas.abap
> +CLASS ZCL_EXCEL_STYLES IMPLEMENTATION.
```suggestion
CLASS zcl_excel_styles IMPLEMENTATION.
```

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel_styles_cond.clas.abap
> +CLASS ZCL_EXCEL_STYLES_COND IMPLEMENTATION.
```suggestion
CLASS zcl_excel_styles_cond IMPLEMENTATION.
```

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel_worksheet.clas.abap
> +CLASS ZCL_EXCEL_WORKSHEET IMPLEMENTATION.
```suggestion
CLASS zcl_excel_worksheet IMPLEMENTATION.
```

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel_worksheets.clas.abap
> +CLASS ZCL_EXCEL_WORKSHEETS IMPLEMENTATION.
```suggestion
CLASS zcl_excel_worksheets IMPLEMENTATION.
```

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel_writer_csv.clas.abap
> +CLASS ZCL_EXCEL_WRITER_CSV IMPLEMENTATION.
```suggestion
CLASS zcl_excel_writer_csv IMPLEMENTATION.
```

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel_writer_huge_file.clas.abap
> +CLASS ZCL_EXCEL_WRITER_HUGE_FILE IMPLEMENTATION.
```suggestion
CLASS zcl_excel_writer_huge_file IMPLEMENTATION.
```

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel_writer_xlsm.clas.abap
> +CLASS ZCL_EXCEL_WRITER_XLSM IMPLEMENTATION.
```suggestion
CLASS zcl_excel_writer_xlsm IMPLEMENTATION.
```

2022-01-01 10:51 UTC, sandraros commented on src/zcl_excel_writer_2007.clas.abap
> +CLASS ZCL_EXCEL_WRITER_2007 IMPLEMENTATION.
```suggestion
CLASS zcl_excel_writer_2007 IMPLEMENTATION.
```

2022-01-01 11:40 UTC, larshp commented
reopen?

2022-01-01 11:46 UTC, merged