added METHOD convert_to_table.
abap2xlsx/abap2xlsx pull request #999
Opened 2022-03-10 06:01 UTC by boy0korea

METHOD convert_to_table.
* For excel upload, This is counterpart to BIND_TABLE
* This method has 2 exporting parameters.
* ER_DATA is a reference to internal table of string columns. intend to get raw data without conversion loss.
* ET_DATA is an internal table supplied. There may be losses in the conversion(MOVE-CORRESPONDING).

**Request** from: https://github.com/boy0korea/ABAP2XLSX_HELPER/issues/1#issue-1144673227

2022-03-14 08:42 UTC, AndreaBorgia-Abo commented
Before I begin the review, one quick question: have you noticed that now the demos and the main library are split into two distinct repositories? We would need a demo for this new method and that demo goes into the new ["demos" repository](https://github.com/abap2xlsx/demos).

2022-03-30 17:39 UTC, AndreaBorgia-Abo commented
@boy0korea do you have time for the demo? No pressure, just want to know if I should take care of that.

2022-08-25 05:13 UTC, larshp commented
1 issue from linter: is https://github.com/abap2xlsx/abap2xlsx/pull/1056 waiting to be merged

2022-08-25 07:18 UTC, AndreaBorgia-Abo commented
@boy0korea could you please look at the linter messages?
Also, what about the demo program?

2022-08-26 01:34 UTC, boy0korea commented
> @boy0korea could you please look at the linter messages? Also, what about the demo program?

demo: https://github.com/abap2xlsx/demos/pull/23

2022-08-27 15:01 UTC, AndreaBorgia-Abo requested changes
Have a look at the suggestions, no big deal since the code works with the demo.
I'll fix the linter error in a moment.
Good job and, once again, welcome on board!

2022-08-27 15:01 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +    METHODS convert_to_table
```suggestion
    "! excel upload, counterpart to BIND_TABLE
    "! @parameter it_field_catalog | field catalog, used to derive correct types
    "! @parameter iv_begin_row | starting row, by default 2 to skip header
    "! @parameter et_data | generic internal table, there may be conversion losses
    "! @parameter er_data | ref to internal table of string columns, to get raw data without conversion losses.
    METHODS convert_to_table
```

2022-08-27 15:01 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +    METHODS convert_to_table
@larshp I'm not entirely sure how back in time we can go with this comment style, but I'd like it better this way if at all possible. EDIT: never mind, I guess the linter doesn't really care about what is in a comment

2022-08-27 15:01 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +* ET_DATA is an internal table supplied. There may be losses in the conversion(MOVE-CORRESPONDING).
```suggestion

```

2022-08-27 15:01 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +* ET_DATA is an internal table supplied. There may be losses in the conversion(MOVE-CORRESPONDING).
Goes together with earlier suggestion, ignore if the one above is rejected

2022-08-27 15:01 UTC, AndreaBorgia-Abo commented on src/zcl_excel_worksheet.clas.abap
> +*    ENDIF.
```suggestion

```

2022-08-27 15:06 UTC, AndreaBorgia-Abo commented
> 1 issue from linter: is #1056 waiting to be merged

How do we merge this? It's in another branch which requires this to be merged first which requires the linter to be happy. I'd simply fix the issue in the PR branch and be on my way.

2022-08-29 16:04 UTC, merged